### PR TITLE
Adding variable table names for session store

### PR DESCRIPTION
**Pull request by mihok**
It would be nice to be able to have the option to change the session table name, I've made basic changes to allow this but haven't added any additional tests.

### CODE REVIEW

**Comment by chill117** [comment]
You are not the first to bring this up actually. I won't merge this pull request, because it doesn't include any new tests to go along with the new option. Also, there is a potential security issue:
```js
	var sql = 'SELECT `data` FROM `' + this.options.databaseTable + '` WHERE `session_id` = ? LIMIT 1'
	var params = [ session_id ]

	this.connection.query(sql, params, function(error, rows) {
		// ..
	})
```

In the above code, you're injecting the new `databaseTable` option directly into the SQL. The safer way would be to do this:
```js
	var sql = 'SELECT `data` FROM ?? WHERE `session_id` = ? LIMIT 1'
	var params = [ this.options.databaseTable, session_id ]

	this.connection.query(sql, params, function(error, rows) {
		// ..
	})
```
You always want to pass values from variables as parameters. Special note for this particular situation:
Table names and column names are "[query identifiers](http://dev.mysql.com/doc/refman/5.0/en/identifier-qualifiers.html)" and are treated a bit differently than ordinary values in [node-mysql](https://github.com/felixge/node-mysql#escaping-query-identifiers).

**Comment by mihok** [comment]
Sure, I figured this would be the case but I was in a hurry at work so I couldn't round out my PR properly. Thanks for the feedback, expect some tests and no sql injections coming up soon ;)

**Comment by chill117** [comment]
@mihok Still planning to make the changes to this pull request?

**Comment by chill117** [comment]
I implemented this feature for version 0.4.0.

**Pull request closed without merging**
