### PR TITLE
Allow for larger session data in sessions table.

### PR DESCRIPTION
**Pull request by pr1ntr**
make data column longtext instead of text to accommodate federated login sessions (ie, twitter)

### CODE REVIEW

**Comment by chill117** [comment]
Is it really a good idea to allow 4 GB of data per session? Wouldn't 16 MB (with `MEDIUMTEXT`) enough?

Reference:
```
      Type | Maximum length
-----------+-------------------------------------
  TINYTEXT |           255 (2 8−1) bytes
      TEXT |        65,535 (216−1) bytes = 64 KiB
MEDIUMTEXT |    16,777,215 (224−1) bytes = 16 MiB
  LONGTEXT | 4,294,967,295 (232−1) bytes =  4 GiB
```

**Comment by HoldYourWaffle** [comment]
Is there a reason why it wouldn't be a good idea to *allow* 4GB of session data? Actually having that much data is obviously a big performance concern, but is that really a reason to put a hard-limit on the user? I can't imagine a use case right now where you'd actually need more than 16 MB of session data, but you never know.

Besides, wouldn't it be possible to just make this a configurable option? That would probably help with #91 too (although I'm not sure if queries need to be structured differently for JSON columns, haven't used them yet).

**Comment by pr1ntr** [comment]
4gb of json is excessive. However, yes it should be configurable, and #91 makes sense if for whatever reason the user wants to query the data object.

**Comment by chill117** [comment]
See #100  - new PR to add a test. I couldn't push any commits to your remote.

**Pull request closed without merging**
